### ISSUE TITLE
AssertionError: Series are different

### ISSUE THREAD

**Issue by ignatenkobrain** [mwaskom/moss#17]
```python
======================================================================
FAIL: moss.tests.test_statistical.TestRemoveUnitVariance.test_remove_by_group
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/moss-0.3.4/moss/tests/test_statistical.py", line 559, in test_remove_by_group
    pdt.assert_series_equal(grp.value.mean(), grp.value_within.mean())
  File "/usr/lib64/python2.7/site-packages/pandas/util/testing.py", line 929, in assert_series_equal
    assert_attr_equal('name', left, right, obj=obj)
  File "/usr/lib64/python2.7/site-packages/pandas/util/testing.py", line 708, in assert_attr_equal
    left_attr, right_attr)
  File "/usr/lib64/python2.7/site-packages/pandas/util/testing.py", line 798, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Series are different

Attribute "name" are different
[left]:  value
[right]: value_within
```

**Comment by mwaskom** [comment]
This isn't very helpful without knowing about what platform you're on, the versions of the relevant libraries, etc.

**Comment by ignatenkobrain** [comment]
https://copr-be.cloud.fedoraproject.org/results/ignatenkobrain/neurofedora/fedora-rawhide-x86_64/00133125-python-moss/root.log.gz

Which components I should send versions?

**Comment by mwaskom** [comment]
Ok, thanks for the wall of text. Do you think you could maybe just write a few sentences about what you are trying to do?

**Comment by ignatenkobrain** [comment]
I'm trying to package RPM for Fedora and I'm running tests when packaging. And this is only one test which fails.

**Comment by mwaskom** [comment]
I don't know what RPM is, but this package is my personal library of random utility functions. If you can't get it to build, I'm sorry, but I'm not going to spend a lot of time making it work on a system I don't use or have any information about.
