### ISSUE TITLE
mosaic issue

### ISSUE THREAD

**Issue by iancballard** [mwaskom/moss#19]
I am getting an "ValueError: operands could not be broadcast together with shapes (64,64,30) (64,30,64) " error when using Mosaic:

m = Mosaic(orig,mask,mask, step = 1)

What's strange is that 

print nib.load(orig).shape
print nib.load(mask).shape

returns (64,64,30) for both.

And

m = Mosaic(orig,mask, step = 1)

works fine.

This issue is coming up in the report for the functional mask step of the lyman preproc workflow.

**Comment by mwaskom** [comment]
what version nibabel?

**Comment by iancballard** [comment]
2.0.2

**Comment by mwaskom** [comment]
strange indeed!

**Comment by mwaskom** [comment]
Do you still have this issue?

**Comment by iancballard** [comment]
No, it resolved itself after I updated all my packages and pulled the latest version from your git. Sorry I forgot to close this.
