### ISSUE TITLE
wonky double gamma HRF

### ISSUE THREAD

**Issue by iancballard** [mwaskom/moss#22]
Hi Michael,

I was playing around the with DesignMatrix class and I am a little confused by the HRFs. They don't come out looking quite like the canonical HRF. It looks like perhaps the code is not adjusting for different TRs, although I am having trouble tracking down the source of the issue:

from moss import glm
import pandas as pd
import seaborn as sns
%matplotlib inline

design = pd.DataFrame({'condition':['test'],
                      'onset': [0],
                      'duration': [2],
                     })

#convolve 
hrf = glm.GammaDifferenceHRF()
model = glm.DesignMatrix(design = design, tr = 1.0, ntp = 14,
                         hrf_model = hrf, hpf_cutoff = 128)
sns.tsplot(model.design_matrix.values.flatten())

![double_gamma](https://cloud.githubusercontent.com/assets/5826949/24384178/d7b1cdc8-1316-11e7-8747-189ba51ce2e2.png)

**Comment by mwaskom** [comment]
This is an artifact of the highpass filter.

**Comment by mwaskom** [comment]
Did this solve the problem?
