### ISSUE TITLE
FIR oversampling

### ISSUE THREAD

**Issue by iancballard** [mwaskom/moss#40]
small issue with default parameter values (I think this is unexpected behavior). The FIR class sets oversampling = 1, but if you don't set oversampling = 1 in the DesignMatrix call, then the frame times get messed up and FIR convolution doesn't work as expected. Because the default value is 16 in DesignMatrix, the FIR convolution doesn't work unless without this parameter set properly.

**Comment by mwaskom** [comment]
Project archived; improved design matrix code is in lyman.
